@startuml
'https://plantuml.com/component-diagram



Actor User as user

user ..> [omnitravel]

[omnitravel] --> "passes data"[parser]
[omnitravel] --> "Load/save"[storage]
[omnitravel] --> "uses" [ui]
[parser] --> "uses" [ui]
[parser] --> "uses" [exchangerateapi]
[parser] --> "uses" [errorhandlers]
[storage] --> "uses" [travelactivitytype]
[travelactivitytype] --> "uses" [ui]
[travelactivitytype] --> "uses" [errorhandlers]
[errorhandlers] --> "uses" [ui]
[parser] --> "uses" [travelactivitytype]
folder "omni.txt" as folder
folder .. [storage]

@enduml