@startuml
'https://plantuml.com/sequence-diagram

actor User

participant "tagCommand(line: String, list: TravelActivityList)" as tagCommandMethod
participant "list: TravelActivityList" as TravelActivityListInstance
participant "OmniExceptionInstance: OmniException" as OmniExceptionInstance

User -> tagCommandMethod: tagCommand(line, list)
activate tagCommandMethod

tagCommandMethod -> tagCommandMethod: line.split(" ")

alt command.length == 3 && isNumeric(command[1])
    tagCommandMethod -> tagCommandMethod: int listNumber = Integer.parseInt(command[1])
    activate tagCommandMethod

    tagCommandMethod -> tagCommandMethod: String tag = command[2]
    activate tagCommandMethod
    tagCommandMethod -> TravelActivityListInstance: tagActivity(listNumber, tag)
    activate TravelActivityListInstance 
    TravelActivityListInstance --> tagCommandMethod:
    deactivate TravelActivityListInstance
    deactivate tagCommandMethod

else command.length == 2
    tagCommandMethod -> OmniExceptionInstance: OmniException("Please specify a tag name")
    activate OmniExceptionInstance
    deactivate OmniExceptionInstance
    deactivate tagCommandMethod

else
    tagCommandMethod -> OmniExceptionInstance: OmniException("Please specify which task to tag")
    activate OmniExceptionInstance
    deactivate OmniExceptionInstance
    deactivate tagCommandMethod
end
@enduml