@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
User -> OmniTravel : "totalexpense /type Food"
OmniTravel -> Parser : totalExpenseCommand(line, list)
   Parser -> TravelActivityList : totalExpense(type)
   loop size of travelActivities ArrayList
      opt activity type matches the type the user inputed
         TravelActivityList -> TravelActivity: getExpense()
         TravelActivity --> TravelActivityList:
         TravelActivityList -> TravelActivityList: total += expense

      end
   end
TravelActivityList --> Parser
Parser --> OmniTravel
OmniTravel --> User
@enduml