@startuml
'https://plantuml.com/sequence-diagram



actor User as user

box OmniTravel
participant ":OmniTravel" as OmniTravel

box Ui
participant ":Ui" as Ui

box Parser
participant ":Parser" as Parser
end box

box TravelActivityType
participant ":TravelActivityList" as TravelActivityList
participant ":TravelActivity" as TravelActivity
end box

user -> OmniTravel : "update 1 /date 2019-12-12 /duration 2 hours"
activate OmniTravel
OmniTravel -> Ui : printLine()
activate Ui
Ui --> OmniTravel
deactivate Ui
OmniTravel-> Parser : updateCommand(line,list)
activate Parser
Parser -> TravelActivityList: updateTravelActivity(traveActivityNumber, date, duration)
activate TravelActivityList
TravelActivityList -> TravelActivity: setDate
activate TravelActivity
TravelActivity --> TravelActivityList
deactivate TravelActivity
TravelActivityList -> TravelActivity: setDuration
activate TravelActivity
TravelActivity --> TravelActivityList
deactivate TravelActivity
TravelActivityList --> Parser
deactivate TravelActivityList
Parser -->OmniTravel
deactivate Parser
OmniTravel-> Ui : printLine()
activate Ui
Ui -->OmniTravel
deactivate Ui
OmniTravel --> user
deactivate OmniTravel


@enduml